# Project information
site_name: 'Run2biz Developers'
site_description: 'Documentation for Developers 4biz'
site_author: 'Run2biz'
site_url: 'https://developers.run2biz.com'

# Repository
#repo_name: 'run2bizdocs/developers'
#repo_url: 'https://github.com/run2bizdocs/developers'

# Copyright
copyright: 'Copyright &copy; 2021 Run2biz'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  static_templates:
        - home.html
  include_sidebar: false
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/images/run2biz-logo.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra_css:
  - 'assets/stylesheets/extra.css'
  - 'assets/stylesheets/home.css'

# Customization
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/run2biz'
    - type: 'facebook'
      link: 'https://www.facebook.com/run2biz'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/run2biz'

# Google Analytics
# Habilitar após a criação da política de privacidade
#google_analytics:
#  - 'UA-131806581-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown

# Generate page .html
use_directory_urls: false

nav:
  - Home:
    - 'https://developers.run2biz.com/en-us/index.html'
  - DEV:
    - Get Started:
      - index.md
      - get-started/configure-webservices.md
      - get-started/load-webservice-script.md
      - get-started/register-webservice.md
    - APIs 4biz:
      - api/apis.md
    - Webservice:
      - webservice/data-export.md
      - webservice/webservices-docs.md
      - webservice/webservices-esp.md
      - webservice/webservices-build.md
    - Toolkit:
      - Scripts:
        - toolkit/script/change-sla.md
  - Run2biz Corporation:
    - 'https://www.run2biz.com/'
#  - Blog:
#    - 'http://pt.blog.run2biz.com'
